version: '3.7'

services:
  textmap:
    build: .
    command: gunicorn textmap.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - /private/var/log/develop/textmap:/var/log/textmap
      - static_volume:/home/nonroot/textmap/staticfiles
      - media_volume:/home/nonroot/textmap/mediafiles
    expose:
      - 8000
    env_file:
      - docker/.env.prod
    depends_on:
      - postgres
  postgres:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - docker/.env.prod
  nginx:
    build: ./docker/nginx
    volumes:
      - static_volume:/home/nonroot/textmap/staticfiles
    ports:
      - 1337:80
    depends_on:
      - textmap

volumes:
  postgres_data:
  static_volume:
  media_volume: