version: '3.7'

services:
  web:
    build: .
    command: python textmap/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - /private/var/log/develop/textmap:/var/log/textmap
    ports:
      - 8000:8000
    env_file:
      - docker/.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - docker/.env.dev

volumes:
  postgres_data: