version: '3.7'

services:
  textmap:
    build: .
    command: gunicorn textmap.wsgi:application --bind 0.0.0.0:8000
#    command: python textmap/manage.py runserver 0.0.0.0:8000
    volumes:
      - /private/var/log/develop/textmap:/var/log/textmap
      - static_volume:/home/app/textmap/staticfiles
      - media_volume:/home/app/textmap/mediafiles
    ports:
      - 8000:8000
    env_file:
      - docker/.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - docker/.env.prod

volumes:
  postgres_data:
  static_volume:
  media_volume: